### PR TITLE
relative header sizes and ensure h5 is not too small

### PR DESCRIPTION
**Pull request by mattmilten**
This fixes https://github.com/Gurobi/docs-optimizer/issues/305.

### CODE REVIEW

**Comment by rluce** [comment]
Looks good on paper, any way how I could assess the effect on the docs-optimizer repo beforehand?  Should we merge it into a 'dev' branch of gurobi-sphinxtheme that I can then pull into a local build of the docs more easily?

**Review by rluce — APPROVED** [review]

**Comment by mattmilten** [comment]
I guess it's easiest to check out that branch and build locally - that's what I did to fine-tune it.

**Comment by mattmilten** [comment]
I don't think it's worth it to design a proper dev environment for this workflow as changes to the theme should be rare.

**Comment by mattmilten** [comment]
argh, I changed the target branch to `dev` and now some more changes creeped into this PR.

**Comment by mattmilten** [comment]
cleaned it up

**Comment by rluce** [comment]
I verified manually with docs-optimizer, the heading sizes look good!  So what's left to do is...
1. Merge dev into main here
2. Fire the rebuild canon for all the repos that use the theme

I'll leave that for @mattmilten or @simonbowly .

**Comment by mattmilten** [comment]
@simonbowly over to you - I am not sure what's the best way to trigger and deploy a rebuild

**Comment by simonbowly** [comment]
Done, and looks good. Thanks @mattmilten!

**Pull request merged**
